.TH Geoeasy 1 "26 Dec 2018" "3.1.1" "User Manual"
.SH NAME
.B geoeasy
\- land surveying calculation, network adjustment, digital terrain models, regression calculation
.SH DESCRIPTION
Surveying calculation, network adjustment, digital terrain models, regression calculation.
Volunteers are wellcome! Send us error reports, feature requests through the issue tracker.
Clone the repository, change the code and send us back a pull request to include your enchacement in the core system.

.SH SYNOPSIS
.B geoeasy [OPTIONS] [data-file] [tcl-script]
.SH OPTIONS
.TP
.B \-\-help [string]
Print help info and exit {authors, modules, version}.
.TP
.B \-\-lang [string]
Switch to a different language {hun, eng, ger, rus, cze}, default=auto.
.TP
.B \-\-log [string]
Select log {path/to/file.log | stdout | stderr}, default=~/geo_easy.log
.SH EXAMPLE
geoeasy --lang hun ~/demodata/test1.geo ./startup.tcl
.SH SEE ALSO
geofindkey (1)
.SH AUTHOR
Copyright (c) 2017, Zoltan Siki <zsiki@github.com>.

All rights reserved.
